Repository hubiinetwork/nahmii-cli, pull requests merged in 2018-08, with the labels that each got.

#2 Feature/balance
  README.md
  package-lock.json
  package.json
  src/commands/show-commands/balance.js
  src/commands/show-commands/payments.js
  src/commands/show.js
  src/sdk/balances-model.js
  src/sdk/payment-model.js
  src/sdk/payment-model.spec.js
  src/sdk/receipts-model.js
  src/sdk/striim-request.js
  src/sdk/striim-request.spec.js
  src/sdk/tokens-model.js
  src/sdk/utils.js
Labels: enhancement

#7 Feature/deposit
  package-lock.json
  package.json
  src/commands/config.js
  src/commands/deposit.js
  src/commands/deposit.spec.js
  src/commands/pay.js
  src/commands/pay.spec.js
  src/commands/show-commands/balance.js
  src/commands/show-commands/payments.js
  src/commands/show-commands/receipts.js
  src/commands/show-commands/tokens.js
  src/config.js
  src/sdk/abis/ClientFund.json
  src/sdk/abis/erc20.json
  src/sdk/balances-model.js
  src/sdk/client-fund-contract.js
  src/sdk/erc20-contract.js
  src/sdk/identity-model.js
  src/sdk/index.js
  src/sdk/payment.js
  src/sdk/payment.spec.js
  src/sdk/receipts-model.js
  src/sdk/striim-provider.js
  src/sdk/striim-provider.spec.js
  src/sdk/striim-request.js
  src/sdk/striim-request.spec.js
  src/sdk/tokens-model.js
  src/sdk/utils.js
  src/sdk/wallet.js
  src/sdk/wallet.spec.js
Labels: enhancement

#8 fix pending payments
  src/commands/pay.spec.js
  src/commands/show-commands/payments.js
  src/commands/show-commands/payments.spec.js
Labels: bug

#9 Update README with deposit command.
  README.md
Labels: enhancement

#10 Release/v1.0.1
  README.md
  package-lock.json
  package.json
  src/commands/pay.spec.js
  src/commands/show-commands/payments.js
  src/commands/show-commands/payments.spec.js
Labels: bug, enhancement

#13 Feature/fix show payments filtering
  package-lock.json
  package.json
  src/commands/show-commands/payments.js
  src/commands/show-commands/payments.spec.js
Labels: bug

#14 Fixes a few bugs
  package-lock.json
  package.json
  src/commands/deposit.js
  src/commands/deposit.spec.js
  src/commands/pay.js
  src/commands/pay.spec.js
Labels: bug

#16 Feature/sdk
  package-lock.json
  package.json
  src/commands/config.js
  src/commands/deposit.js
  src/commands/deposit.spec.js
  src/commands/pay.js
  src/commands/pay.spec.js
  src/commands/show-commands/balance.js
  src/commands/show-commands/payments.js
  src/commands/show-commands/payments.spec.js
  src/commands/show-commands/receipts.js
  src/commands/show-commands/tokens.js
  src/config.js
  src/sdk/abis/ClientFund.json
  src/sdk/abis/erc20.json
  src/sdk/client-fund-contract.js
  src/sdk/erc20-contract.js
  src/sdk/identity-model.js
  src/sdk/index.js
  src/sdk/payment.js
  src/sdk/payment.spec.js
  src/sdk/striim-provider.js
  src/sdk/striim-provider.spec.js
  src/sdk/striim-request.js
  src/sdk/striim-request.spec.js
  src/sdk/utils.js
  src/sdk/wallet.js
  src/sdk/wallet.spec.js
Labels: technical debt

#19 Feature/stringify show receipts
  package-lock.json
  package.json
  src/commands/show-commands/receipts.js
Labels: bug
