Repository hubiinetwork/nahmii-cli, pull requests merged in 2019-08, with the labels that each got.

#73 Gas Price on Claim Command
  package-lock.json
  package.json
  src/commands/claim-nii.js
  src/commands/claim-nii.spec.js
  src/commands/deposit.js
  src/config.js
Labels: bug, enhancement, technical debt

#75 Feature/ropsten 3 1 3
  package.json
Labels: enhancement

#76 new mainnet contracts
  package.json
Labels: bug

#77 Upgrade to latest SDK/mainnet contracts
  package.json
Labels: bug
